---
title: "Creating St. Lucia Graphs and Demographics tables"
output: html_document
date: "2023-12-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
```

```{r}
economic_growth_data<- read.csv("St_Lucia/caricom_growth_data.csv")
caricom_country_list<- c("Antigua and Barbuda",
                          "Bahamas, The",
                          "Barbados",
                          "Belize",
                          "Dominica",
                          "Grenada",
                          "Guyana",
                          "Haiti",
                          "Jamaica",
                          "St. Kitts and Nevis",
                          "St. Lucia",
                          "St. Vincent and the Grenadines",
                          "Suriname",
                          "Trinidad and Tobago",
                          "Caribbean small states")

caricom_growth_data<- economic_growth_data |> filter(Country.Name %in% caricom_country_list) |> 
                            select(c(Country.Name,X1978:last_col()))

caricom_growth_data$Country.Name<- ifelse(caricom_growth_data$Country.Name=="Caribbean small states",
                                          "CARICOM", caricom_growth_data$Country.Name)

col<- str_replace(colnames(caricom_growth_data),"X","")
colnames(caricom_growth_data)<- col

caricom_growth_data_1<- as.data.frame(t(caricom_growth_data), row.names=c(1:46))
colnames(caricom_growth_data_1)<- caricom_country_list
caricom_growth_data_1<- caricom_growth_data_1[-1,]

years<- c(1978:2022)
caricom_growth_data_1<- caricom_growth_data_1 |> mutate(
                                              Year = years, .before=1
)

#Let's write this out into a csv:

write.csv(caricom_growth_data_1,"caricom_growth.csv")

```

Making the economic growth graph:

```{r}
caricom_growth<- read.csv("St_Lucia/caricom_growth.csv") |> select(Year:Caribbean.small.states)
caricom_growth$Year<- ymd(caricom_growth$Year, truncated=2L)
colnames(caricom_growth)<- c("Year","Antigua and Barbuda", "The Bahamas","Barbados", "Belize",
                             "Dominica","Grenada", "Guyana","Haiti", "Jamaica",
                             "St.Kitts and Nevis", "St. Lucia", "St. Vincent and the Grenadines",
                             "Suriname", "Trinidad and Tobago", "CARICOM")

ggplot(caricom_growth, aes(x=Year))+
         geom_line(aes(y=`St. Lucia`, color = 'St. Lucia'))+
         geom_line(aes(y= CARICOM, color = 'CARICOM'))+
         ggtitle("Economic Growth of Saint Lucia relative to rest of CARICOM")+
         xlab("Year")+ylab('% Change in GDP')+
         scale_color_manual(name="Country", values = c('#581845','#FFC300') )
```

```{r}

antigua<- caricom_growth |> select(Year,Antigua.and.Barbuda)
ggplot(antigua, aes(x="Year", y= Antigua.and.Barbuda, group =1))+ 
         geom_line()

```



```{r}
pop_by_age<- read.csv("St_Lucia/IDB_12-18-2023.csv") |> select(Year, GROUP,
                                                      Male.Population,
                                                      Female.Population,
                                                      )

pyramid_frame<- pop_by_age |> pivot_longer(cols = c(Male.Population,Female.Population),names_to = "Gender", values_to="Population") 

pyramid_frame$Gender <- ifelse(pyramid_frame$Gender=="Male.Population", "M","F")
pyramid_frame$Year<- ymd(pyramid_frame$Year, truncated=2L)

pyramid_frame<- pyramid_frame |> mutate(Population=
                                          ifelse(Gender=="M", Population*(-1),
                                            Population)) |> filter(GROUP!= "100+") |>filter(GROUP!="TOTAL") 


range_pop<- range(pyramid_frame$Population)
breaks_pop<- pretty(range_pop, n=7)


ggplot(data=pyramid_frame, aes(x=GROUP, y = Population, fill=Gender))+
  geom_bar(stat="identity")+coord_flip()+
  scale_fill_manual(name = "Gender",labels = c("Male", "Female"),
                      values = c('#581845','#FFC300'))+
  ylab("Age Groups)
  scale_y_continuous(breaks  = breaks_pop,
                       labels = abs(breaks_pop))


```

